#!/bin/csh

set command = "time ./grid_multipolesAVX -box 2000 -scale 1 -rmax 90 -ngrid 40"
echo command
echo "Did you re-compile grid_multipoles for the correct NBIN?"

set tmp = /mnt/ssd/ted
set in = LasDamas
set out = LasDamas.v05
set errlog = $out/errlog
set ranroot = ldam

mkdir $out
rm -i $errlog
touch $errlog

#set root = ldam.01a_no.real
#foreach root ( \
#    ldam.01a_no.real \
#    ldam.01b_no.real \
#    ldam.01c_no.real \
#    ldam.01d_no.real \
#    ldam.02a_no.real \
#    ldam.02b_no.real \
#    ldam.02c_no.real \
#    ldam.02d_no.real \
#)

foreach root ( \
	ldam.10a_no.real \
	ldam.10b_no.real \
	ldam.10c_no.real \
	ldam.10d_no.real \
	ldam.11a_no.real \
	ldam.11b_no.real \
	ldam.11c_no.real \
	ldam.11d_no.real \
	ldam.12a_no.real \
	ldam.12b_no.real \
	ldam.12c_no.real \
	ldam.12d_no.real \
	ldam.13a_no.real \
	ldam.13b_no.real \
	ldam.13c_no.real \
	ldam.13d_no.real \
	ldam.14a_no.real \
	ldam.14b_no.real \
	ldam.14c_no.real \
	ldam.14d_no.real \
	ldam.15a_no.real \
	ldam.15b_no.real \
	ldam.15c_no.real \
	ldam.15d_no.real \
	ldam.16a_no.real \
	ldam.16b_no.real \
	ldam.16c_no.real \
	ldam.16d_no.real \
	ldam.17a_no.real \
	ldam.17b_no.real \
	ldam.17c_no.real \
	ldam.17d_no.real \
	ldam.18a_no.real \
	ldam.18b_no.real \
	ldam.18c_no.real \
	ldam.18d_no.real \
	ldam.19a_no.real \
	ldam.19b_no.real \
	ldam.19c_no.real \
	ldam.19d_no.real \
)

    echo $root
    echo $root >> $errlog

    set multfile = $tmp/$root.mult

    # Get the data and run it, with storage
    gunzip -c $in/$root.dat.gz > $tmp/$root.dat

    echo "Starting DDD" >> $errlog
    date >> $errlog
    ($command -in $tmp/$root.dat -save $multfile \
	    > $out/$root.ddd.out) >>& $errlog

    echo Done with DDD


    # Get a base random and run it, with inversion
    gunzip -c $in/$ranroot.ran.00.gz > $tmp/$root.ran.0

    echo "Starting RRR" >> $errlog
    date >> $errlog
    ($command -in $tmp/$root.ran.0 -invert \
	    > $out/$root.rrr.out) >>& $errlog

    echo Done with RRR

    cat $tmp/$root.dat >> $tmp/$root.ran.0

    echo "Starting D-R check" >> $errlog
    date >> $errlog
    ($command -in $tmp/$root.ran.0 \
	    > $out/$root.ch0.out) >>& $errlog

    rm $tmp/$root.ran.0
    echo Done with D-R 0 check

    # Now make D-R and run that, with loading
    foreach n ( 00 01 02 03 04 05 06 07 08 09 )
	cp -f $tmp/$root.dat $tmp/$root.ran.$n
	gunzip -c $in/$ranroot.ran.$n.gz >> $tmp/$root.ran.$n

	echo "Starting D-R $n" >> $errlog
	date >> $errlog
	($command -in $tmp/$root.ran.$n -load $multfile \
		> $out/$root.r$n.out) >>& $errlog

	rm $tmp/$root.ran.$n
	echo Done with D-R $n

    end    # foreach D-R loop

end    # foreach root loop
