#!/bin/csh

set command = "time ./grid_multipolesAVX -box 3000 -scale 1 -rmax 50 -ngrid 60"
echo command
echo "Did you re-compile grid_multipoles for the correct NBIN?"

set tmp = /mnt/ssd/ted
set in = DR10n
set root = sdss.dr10n
set out = DR10n.v03
set errlog = $out/errlog

#if (-e $out) 
#    echo "Directory $out exists"
#    exit
#endif

mkdir $out
rm -i $errlog

set multfile = $tmp/$root.mult

# Get the data and run it, with storage
gunzip -c $in/$root.data.gz > $tmp/$root.data

echo "Starting DDD" >> $errlog
date >> $errlog
($command -in $tmp/$root.data -save $multfile \
	> $out/$root.ddd.out) >&! $errlog

echo Done with DDD


# Get a base random and run it, with inversion
gunzip -c $in/$root.ran.00.gz > $tmp/$root.ran.0

echo "Starting RRR" >> $errlog
date >> $errlog
($command -in $tmp/$root.ran.0 -invert \
	> $out/$root.rrr.out) >>& $errlog

echo Done with RRR

cat $tmp/$root.data >> $tmp/$root.ran.0

echo "Starting D-R check" >> $errlog
date >> $errlog
($command -in $tmp/$root.ran.0 \
	> $out/$root.ch0.out) >>& $errlog

rm $tmp/$root.ran.0
echo Done with D-R 0 check

# Now make D-R and run that, with loading
foreach n ( 00 01 02 03 04 05 06 07 08 09 )
cp -f $tmp/$root.data $tmp/$root.ran.$n
gunzip -c $in/$root.ran.$n.gz >> $tmp/$root.ran.$n

echo "Starting D-R $n" >> $errlog
date >> $errlog
($command -in $tmp/$root.ran.$n -load $multfile \
	> $out/$root.r$n.out) >>& $errlog

rm $tmp/$root.ran.$n
echo Done with D-R $n

end    # foreach D-R loop
